apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: echo
spec:
  rules:
    - host: edx-learner-attrition.southcentralus.cloudapp.azure.com
      http:
        paths:
          - backend:
              serviceName: echoservice
              servicePort: 80
            path: /
  # # This section is only required if TLS is to be enabled for the Ingress
    # tls:
    #     - hosts:
    #         - www.example.com
    #       secretName: example-tls
