apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: learnerattrition.azurecr.io/learner-attrition-pipeline
  imagePullSecrets:
  - name: registrykey